CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(40) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email varchar(255) NOT NULL UNIQUE,
    recovery_token varchar(255) NULL
);

CREATE TABLE tasks(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(20) NOT NULL,
    description TEXT,
    done BOOLEAN NOT NULL DEFAULT 0,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER FOREIGN KEY REFERENCES users(id)
);